server:
    port: 9099

spring:
    application:
        name: rabbitmq-provider
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        publisher-returns: true  # 支持消息发送失败返回队列
        publisher-confirms: true  # 开启消息确认机制
        virtual-host: /
        listener:
            simple:
                acknowledge-mode: manual  # 手动确认
                prefetch: 1
        template:
            mandatory: true